nohup: ignoring input
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 39032)
Traceback (most recent call last):
  File "/workspaces/generador-prompts-ia/simple_server.py", line 38, in do_POST
    self.send_json_response(response)
  File "/workspaces/generador-prompts-ia/simple_server.py", line 57, in send_json_response
    self.wfile.write(json.dumps(data, ensure_ascii=False).encode('utf-8'))
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/python/3.12.1/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/python/3.12.1/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/python/3.12.1/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/workspaces/generador-prompts-ia/simple_server.py", line 44, in do_POST
    self.send_error_response(str(e))
  File "/workspaces/generador-prompts-ia/simple_server.py", line 63, in send_error_response
    self.end_headers()
  File "/usr/local/python/3.12.1/lib/python3.12/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/local/python/3.12.1/lib/python3.12/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/python/3.12.1/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
